name: Notify on Main Merge

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            🚀 A new commit was pushed to **main**!
            Repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}
          username: "GitHub Bot"
          avatarUrl: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"