name: Notify on Main Merge

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: "Hello, from Github"
          # webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          # message: "teste"
          # username: "GitHub Bot"
          # avatar: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"