name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: CI - Code Quality, Security, Unit Tests & Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 check_security.py --max-line-length=100

      - name: Run unit tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run security check script
        run: python check_security.py

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  deploy:
    name: CD - Simulated Deployment
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - uses: actions/checkout@v3

      - name: Simulate deployment
        run: |
          mkdir -p deployment
          cp check_security.py deployment/
          echo "Deployed at $(date)" > deployment/deploy_log.txt
